#!/bin/bash

if [ -f artisan ]
then
    php artisan down --retry=60

    php artisan optimize:clear

    git pull origin main
    composer install --no-interaction --prefer-dist --optimize-autoloader

    php artisan migrate --force --seed

    php artisan event:cache
    php artisan optimize

    php artisan queue:restart
    # php artisan horizon:terminate

    php artisan up

    # npm i
    # npm run production
fi
